// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAto1HH6kMZxjo9OmWlFLZOtQ_TPfOOeHM',
    appId: '1:512055642594:web:2eeae476777b4054f5d1bb',
    messagingSenderId: '512055642594',
    projectId: 'movies-app-c7219',
    authDomain: 'movies-app-c7219.firebaseapp.com',
    storageBucket: 'movies-app-c7219.firebasestorage.app',
    measurementId: 'G-8KER6SV36R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGi23XrVDUNTQu7akZD3N-DvRCS8NvKM',
    appId: '1:512055642594:android:7bbecb7d419d7884f5d1bb',
    messagingSenderId: '512055642594',
    projectId: 'movies-app-c7219',
    storageBucket: 'movies-app-c7219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPAxFzXerJtCoBZPE8J4QPd42ReQaqVw',
    appId: '1:512055642594:ios:9460e7de3e2a53e6f5d1bb',
    messagingSenderId: '512055642594',
    projectId: 'movies-app-c7219',
    storageBucket: 'movies-app-c7219.firebasestorage.app',
    iosBundleId: 'com.example.moviesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpPAxFzXerJtCoBZPE8J4QPd42ReQaqVw',
    appId: '1:512055642594:ios:9460e7de3e2a53e6f5d1bb',
    messagingSenderId: '512055642594',
    projectId: 'movies-app-c7219',
    storageBucket: 'movies-app-c7219.firebasestorage.app',
    iosBundleId: 'com.example.moviesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAto1HH6kMZxjo9OmWlFLZOtQ_TPfOOeHM',
    appId: '1:512055642594:web:dec5ede80292895cf5d1bb',
    messagingSenderId: '512055642594',
    projectId: 'movies-app-c7219',
    authDomain: 'movies-app-c7219.firebaseapp.com',
    storageBucket: 'movies-app-c7219.firebasestorage.app',
    measurementId: 'G-L8QX8T99KR',
  );
}
